defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
whitelist:
  - jekyll-redirect-from
plugins:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
